name: Trivy

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  schedule:
    - cron: '10 21 * * 0'

jobs:
  analyse-identity-api:
    name: Analyse Identity Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image from Dockerfile
        run: |
          docker build -f src/NHSD.BuyingCatalogue.Identity.Api/Dockerfile -t docker.io/nhsd/buying-catalogue/identity-api:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner against Identity
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/nhsd/buying-catalogue/identity-api:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-identity-api.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Identity scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-identity-api.sarif'

  analyse-organisations-api:
    name: Analyse Organisations API Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image from Dockerfile
        run: |
          docker build -f src/NHSD.BuyingCatalogue.Organisations.Api/Dockerfile -t docker.io/nhsd/buying-catalogue/organisations-api:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner against Organisations API
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/nhsd/buying-catalogue/organisations-api:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-organisations-api.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Organisations API scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-organisations-api.sarif'
